### ISSUE TITLE
Bug with skin textures

### ISSUE THREAD

**Issue by Bryson0518** [ClubObsidian/DynamicGui#340]
```
[04:47:59 WARN]: java.lang.NoSuchMethodException: com.mojang.authlib.properties.Property.getValue()
[04:47:59 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.bukkit.entity.BukkitPlayerWrapper.getSkinTexture(BukkitPlayerWrapper.java:216)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.replacer.SkinTextureReplacer.lambda$replacement$0(SkinTextureReplacer.java:47)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.shaded.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2550)
[04:47:59 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.shaded.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2548)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.shaded.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2531)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.shaded.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:110)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.shaded.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.replacer.SkinTextureReplacer.replacement(SkinTextureReplacer.java:47)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.registry.replacer.DynamicGuiReplacerRegistryImpl.replace(DynamicGuiReplacerRegistryImpl.java:59)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.manager.ReplacerManagerImpl.replace(ReplacerManagerImpl.java:40)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.gui.SimpleSlot.buildItemStack(SimpleSlot.java:243)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.gui.SimpleGui.populateInventory(SimpleGui.java:126)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.gui.SimpleGui.buildInventory(SimpleGui.java:97)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.manager.GuiManagerImpl.lambda$openGui$7(GuiManagerImpl.java:201)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.util.ThreadUtil.run(ThreadUtil.java:34)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.manager.GuiManagerImpl.lambda$openGui$8(GuiManagerImpl.java:189)
[04:47:59 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
[04:47:59 WARN]:        at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
[04:47:59 WARN]:        at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.manager.GuiManagerImpl.lambda$openGui$9(GuiManagerImpl.java:189)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.util.ThreadUtil.run(ThreadUtil.java:34)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.manager.GuiManagerImpl.openGui(GuiManagerImpl.java:167)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.api.manager.gui.GuiManager.openGui(GuiManager.java:214)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.api.manager.gui.GuiManager.openGui(GuiManager.java:186)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.command.CommandRegistrarImpl.lambda$registerGuiAliasCommand$2(CommandRegistrarImpl.java:91)
[04:47:59 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.core.command.CommandRegistrarImpl.lambda$registerGuiAliasCommand$3(CommandRegistrarImpl.java:79)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.shaded.cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.shaded.cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.shaded.cloud.commandframework.CommandManager.executeCommand(CommandManager.java:189)
[04:47:59 WARN]:        at DynamicGui-Bukkit-6.2.0.jar//com.clubobsidian.dynamicgui.shaded.cloud.commandframework.bukkit.BukkitCommand.execute(BukkitCommand.java:116)
[04:47:59 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[04:47:59 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991)
[04:47:59 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[04:47:59 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[04:47:59 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[04:47:59 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[04:47:59 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2208)
[04:47:59 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2168)
[04:47:59 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[04:47:59 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[04:47:59 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[04:47:59 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[04:47:59 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[04:47:59 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[04:47:59 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[04:47:59 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[04:47:59 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[04:47:59 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[04:47:59 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[04:47:59 WARN]:        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[04:47:59 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[04:47:59 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[04:47:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by virustotalop** [comment]
Fixed in b9f1f4293f6a76a25b3875f6d6d0242760dee169
